using System;

namespace AdjusterOptimizerAPI.Models
{
    /// <summary>
    /// Represents a claim assignment made by the system or a supervisor.
    /// Includes metadata such as score, explanation, and assignment date.
    /// </summary>
    public class Assignment
    {
        /// <summary>
        /// Primary key for the Assignments table.
        /// </summary>
        public int AssignmentId { get; set; }

        /// <summary>
        /// Foreign key referencing the assigned claim.
        /// </summary>
        public int ClaimId { get; set; }

        /// <summary>
        /// Foreign key referencing the adjuster who received the assignment.
        /// </summary>
        public int AdjusterId { get; set; }

        /// <summary>
        /// Date and time the assignment was created.
        /// </summary>
        public DateTime AssignmentDate { get; set; }

        /// <summary>
        /// Score generated by the assignment engine (0.0–100.0).
        /// Represents how strong the match was.
        /// </summary>
        public decimal Score { get; set; }

        /// <summary>
        /// Name of the supervisor or system that created the assignment.
        /// </summary>
        public required string AssignedBy { get; set; }

        /// <summary>
        /// Explanation of why this adjuster was selected.
        /// Useful for transparency and auditing.
        /// </summary>
        public required string Explanation { get; set; }

        /// <summary>
        /// Navigation property for the assigned adjuster.
        /// </summary>
        public required Adjuster Adjuster { get; set; }

        /// <summary>
        /// Navigation property for the assigned claim.
        /// </summary>
        public required Claim Claim { get; set; }
    }
}
